### PR TITLE
Remove T prefixes for TLock, TCond, TThread, TThreadId

### PR DESCRIPTION
**Pull request by def-**
Again just the ones I noticed while coding something simple. I'm wondering whether we should semi-automatically rename all remaining T/P prefixes.

### CODE REVIEW

**Comment by Varriount** [comment]
Looks good to me.

**Comment by Araq** [comment]
These still have the ``T`` prefix because they will eventually be replaced by something with a much better interface that uses the new .locks pragmas etc.

**Comment by reactormonk** [comment]
@Araq so you want to reserve the names without `T` for the new interface?

**Comment by Araq** [comment]
Exactly.

**Pull request closed without merging**
