### PR TITLE
Set executable bit on build.sh.

### PR DESCRIPTION
**Pull request by oderwat**
I am not sure why this is not set already? To me it is an annoyance
that I have to set it manually and then git shows me a change for
that file all the time while working.

### CODE REVIEW

**Comment by Araq** [comment]
What's wrong with ``sh build.sh``? that's easier to type anyway.

**Comment by oderwat** [comment]
Hehe:

Do you know that you can still do that if the x bit is set? ;-)
My solution colors the script in dir listings :)
The x bit on the install.sh in the build.sh script is set explicitly :)
Your solution sucks when using bash :-P "bash build.sh" ;-)
My solution is free as in free beer!
It is Karneval!

BTW: I don't care to much

**Comment by kirbyfan64** [comment]
I still don't see how `sh build.sh` is easier to type than `./build.sh`. The second comes more naturally for me since I'm used to the dot prefix when writing programs.

**Comment by oderwat** [comment]
@kirbyfan64 on a german keyboard sh<space>something is easier then .<Slash(<- shift 7)>build.sh
I guess this is what Araq means. But I could be wrong and there is something else about his way which is superior.

My concern was more what git will do on windows for the x bit or if there are any other problems with that I don't know of.

**Comment by kirbyfan64** [comment]
@oderwat The executable bit will be stored in the repo, but it (obviously) won't appear in the file system.

**Pull request merged**
