### PR TITLE
Add mgetOrPut to support just one probe chase for the common

### PR DESCRIPTION
**Pull request by c-blake**
pattern of either updating or initializing table entries.  Usage example might be like:

```
import tables

when isMainModule:
  proc main() =
    var t = initTable[int, seq[int]](4)
    for i in 1..13:
      t.mgetOrPut(i mod 5, @[]).add(i)
    for k, vs in t.pairs:
      for v in vs:
        if v mod 5 != k:
          echo "error"
  main()
```

or maybe inc(mgetOrPut(tab, key, 0)) for histogram/CountTable like usage or so on.  I'm not sure this is the 100% best interface.  E.g., it doesn't help so much if the update of a freshly initialized value is too different from the update of an existing value.  Still, this mgetOrPut si probably better than nothing or better than exporting `rawGet` and `data`.  The alternate double-search will have the second searched cached for sure, but forcing that is twice as slow for L1 cachable tables.  I can template-ize it and add it to OrderedTable, too, if you want.  I just thought I'd first make a specific proposal via a PR.

### CODE REVIEW

**Comment by c-blake** [comment]
Oh, yeah, and in terms of further backing up "how applicable" the operation is as proposed/use case examples or backup, it's basically the same as what in Python (since 2.0) is called "setdefault" on standard dict()s.  In just the distribution/stdlib of Python 2.7.9 that call is used 101 times in 46 different files.  Only a small portion of that is "testing that feature", too.  In my site-packages, I see it used 1287 times in 414 files.  Obviously Nim is a somewhat different context (its "multimap"/multiple keys for tables in particular), but some feature like this seems "pretty commonly useful" to me.  Nim itself has sets.nim:containsOrIncl, too.  We could also additionally add a 'bool return' fork of this (not unlike the not yet used tables.nim:hasKeyOrPutImpl.  The modifiable value return seems more useful in a tables context, though.

**Comment by Araq** [comment]
Looks good to me, but you added no tests for mgetOrPut? Or did I miss them?

**Comment by fowlmouth** [comment]
New seq is created even when its not necessary. Could it instead use something like this
```nimrod
type Initable = generic x
  init(var x) is void
```
Call init on the value inside the table to avoid copies. User would have to define init()

```nimrod
#this would be possible too as a side effect 
var x: Table[string, int]
x.init
var s: seq[int]
s.init
```

**Comment by Araq** [comment]
@fowlmouth we don't do that for now in the stdlib.

**Comment by c-blake** [comment]
@Araq, I hadn't added any regression/unit tests for either OrPut()s, though I did test them in local programs.  Let me add some tests (tomorrow) before closing out this PR.  Thanks for the patience.

**Comment by fowlmouth** [comment]
could it be a template? lets delay `val` from evaluating as long as possible :+1: :+1:

**Comment by c-blake** [comment]
@Araq - I put in some unit tests for Table for both positive & negative cases in both mgetOrPut and hasKeyOrPut.  They pass with current version.  Should be good to close this PR if you want.

**Pull request merged**
