### PR TITLE
Optional colon

### PR DESCRIPTION
**Pull request by nanoant**
Please do not merge yet, I still need to add some tests. However adding this PR so we can discuss it better on:

http://forum.nim-lang.org/t/1127/3

### CODE REVIEW

**Comment by goob** [comment]
Is there any reason the `of` branches of a `case` wouldn't follow the same rule?

**Comment by nanoant** [comment]
There is no reason. Probably I will add it as next step. Extra commit. I prefer to do atomic commits as much as possible.

**Comment by nanoant** [comment]
Okie, tests added. I think it is ready to be merged. Seems to not break anything in existing tests too.

**Comment by dom96** [comment]
This needs to be put behind a ``#! optionalColons``.

**Comment by nanoant** [comment]
Any reason why!? It does not break existing syntax.

**Comment by kirbyfan64** [comment]
I prefer it with `#! optionalColons`. Even though it doesn't break existing syntax, it just feels "cleaner".

**Comment by dom96** [comment]
I would much prefer for the colon to stay. It is simply more readable. Too many of these optional syntaxes will result in a language that becomes incredibly confusing.

**Comment by nanoant** [comment]
Again, this change does not make colon obsolete, but just optional. You are free to use it. Syntax guidelines may still recommend it to use to, standard libraries may still use colon... it is just not enforced.

Now colon ':' matches more semicolon ';', where it is only required on one-liners. Why don't we force ';' on end-of-line by default!?

**Comment by kirbyfan64** [comment]
Because that's Nim. If you forced a semicolon, you'd be using another language.

This is one of those things that's just...that. There isn't really a hardcore, intense, all-wowing reason. It's just...because it's Nim.

**Comment by nanoant** [comment]
Exactly. Then why this: *I would much prefer for the colon to stay*?, if this change does not remove colon, but makes it just optional when using line break and indent to start block.

Otherwise provide good reasoning why you want to force everyone using colon if compiler can infer that block comes next given next line and indent.

**Comment by dom96** [comment]
Yes, it makes it optional. But I don't want it to be optional, I want all code that I see out in the wild to have these colons where I expect them to be. It might be trivial for compilers to infer this information based on the indentation, but a colon provides a very good clue to human readers.

**Comment by nanoant** [comment]
@dom96 This is exactly opposite to what original requester on forums stated. Again same applies to identifier naming, but Nim gives absolute freedom to use `i_d_e_n_t_i_f_i_e_r` or `iDeNtIfIeRs`.

**Comment by kirbyfan64** [comment]
How 'bout we just wait here for @Araq to give the final call? Usually, when he decides, it happens. :)

**Comment by dom96** [comment]
@Araq already stated that he wanted the ``#! optionalColons``. He also stated that he might not even merge that!

**Comment by dom96** [comment]
There are seriously far more important things that should be implemented than this bike shed. I see absolutely no advantages to optional colons.

**Comment by rbehrends** [comment]
The problem with making colons optional without `#! optionalColons` is that it's no longer possible to have the compiler check that colons are actually there if you want them (i.e. syntax with colons cannot be enforced any longer). There's a difference between creating an alternate syntax because some people may like it and making it the unavoidable default.

**Comment by nanoant** [comment]
Okie, I'll make it enabled as an option, this should be pretty easy to test that option in `parser.nim` `colcom()`.

**Comment by kirbyfan64** [comment]
@rbehrends That makes sense.

**Comment by goob** [comment]
I personally don't care and I think stuff like this is mostly a waste of time, however I don't believe the "compiler check" argument holds much weight. If they're optional, then it becomes purely a matter of style. So while a person may want them, it's not an actual issue if one is missed.

**Comment by rbehrends** [comment]
What @Araq is suggesting is to use Nim's [source code filters](http://nim-lang.org/filters.html).

**Comment by rbehrends** [comment]
> So while a person may want them, it's not an actual issue if one is missed.

It is an issue if you have other tooling that assumes a specific syntax/style. Do not assume that the Nim compiler is the only tool that consumes Nim source code. Syntax highlighters, pretty printers, source code to TeX converters, etc. Many of these tools may not have a complete parser available, may be designed to work only on code fragments, or have to work with code that has minor syntax errors.

**Comment by nanoant** [comment]
Done! Commits updated. Now it requires `optionalColon` directive, similar to `strongSpaces`, eg.:

```nimrod
  #! optionalColon
  if 1+2+3==6
    echo "1+2+3==6"
  else
    echo "impossible!"
```

Btw. I wonder such directive can be placed in projects `.ini` file? So user may decide to put it in one place, instead in each file.

**Comment by oderwat** [comment]
That code in the test looks so wrong without the colons.

**Comment by trustable-code** [comment]
To me it looks cleaner without the colons. And people who are new to programming wonder why there has to be a colon. I think the colon should be omitted for the same reason as curly brackets are omitted.

**Comment by reactormonk** [comment]
With the special syntax `#! optionalColon` it's just gonna be yet another obscure language feature. Either without or not at all.

**Comment by ReneSac** [comment]
The main argument for colons is readability. See python FAQ: https://docs.python.org/2/faq/design.html#why-are-colons-required-for-the-if-while-def-class-statements

That is why people here are so against it. They don't want to read code like that. It is good to have a little redundancy in the language. It is faster to read code with colons, as it gives an unambiguous indication that this line has ended. As that line is just before an indented block, you can't rely on indentation like you can in other multi-line statements.

As for the test file, you don't seem to have specified the output. And there is no test for templates accepting statements as arguments.

**Comment by nanoant** [comment]
I think this Python FAQ is bit biased, see:
zrzut ekranu 2015-04-15 o 23 13 23
^-- yeah sure, the 2nd "easier to read" line has syntax highlight enabled ;)

Please just note that I am not in favor in any syntax, I just prefer to let programmer decide what is better for him.

**Comment by oderwat** [comment]
@nanoant actually they even write that the colon makes syntax highlighting easier :) which may even be the reason why it is active in the second example.

**Comment by nanoant** [comment]
@oderwat Yeah, sure they need a colon which is lexer token, to highlight `if` which is another lexer token ;)

> As for the test file, you don't seem to have specified the output. And there is no test for templates accepting statements as arguments.

@ReneSac Isn't `./tests/showoff/thtml2.nim` such test? I don't quite follow. All I meant that enabling optional colon and running Nim tests and compilation does not break them.

**Comment by reactormonk** [comment]
It's gonna be a bitch to support via syntax highlighting in editors. And nim-mode hl already sucks, no need for more pitfalls.

**Comment by nanoant** [comment]
@reactormonk I concur.

**Comment by nanoant** [comment]
Hereby I close this PR! Let's do something useful.

**Comment by Justin-Marks** [comment]
> It's gonna be a bitch to support via syntax highlighting in editors. And nim-mode hl already sucks, no need for more pitfalls.

Clear language > highlighting

@nanoant 
Please reconsider. A colon is really just an ugly opening brace in disguise. There's no closing brace, so there shouldn't be an opening brace either.

**Comment by nanoant** [comment]
@Justin-Marks why comment on the issue closed 1yr ago?

**Comment by Justin-Marks** [comment]
I don't feel syntax highlighting was a good argument for closing the issue. Is it too late now?

**Comment by kirbyfan64** [comment]
Trust me; I've worked on text editors. It's not "syntax highlighting" as much as autoindent:

```nim
if x
  # Editor should indent.
if x: abc # Editor should NOT indent.
```

The rules for Ruby are usually really complicated due to this

**Comment by Justin-Marks** [comment]
I doubt any Ruby users would want to add colons to the language just to make text editor integration easier.

**Pull request closed without merging**
