### PR TITLE
Add reversed proc to unicode module

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by Varriount** [comment]
Looks good to me.

**Comment by EXetoC** [comment]
how about an iterator?

**Comment by def-** [comment]
@Araq: Thanks, you were right. Much better performance now.

**Comment by Varriount** [comment]
Perhaps `isCombining` should be placed in the unicode module, so that others can take advantage of it?

**Comment by def-** [comment]
> Perhaps isCombining should be placed in the unicode module, so that others can take advantage of it?

Yes, that's one of the things the pull request would do, right?

**Comment by Varriount** [comment]
Oh, sorry, wasn't thinking. For some reason I had thought that the procedure was being put in another module.

**Pull request merged**
