### PR TITLE
Bring back (again) bootstrap.sh executable bit

### PR DESCRIPTION
**Pull request by nanoant**
Reverts "bootstrap.sh: cannot keep exec bit on windows" commit
2d2eca18b8c326f1e3ea9101d00b3370c8c5c290.

We do not need to remove executable bits to workaround old msysGit bug that
shows files having executable bits as modified.

This can and should be addressed by msysGit user either by using latest version
that will treat `bootstrap.sh` as having executable bit because of UNIX Shebang
presence, or setting Git config's `core.fileMode` to false.

See:

http://stackoverflow.com/questions/12193020/file-mode-with-msysgit
http://www.grumpydev.com/2011/01/19/switching-from-cygwin-to-msysgit-git-thinks-everything-has-been-modified/

Quoting Git manual:

  core.fileMode
      If false, the executable bit differences between the index and the
      working copy are ignored; useful on broken filesystems like FAT.
      See git-update-index(1). True by default.

### CODE REVIEW

**Comment by dom96** [comment]
I don't get why this is so important. Can't you simply execute ``sh bootstrap.sh``?

**Comment by nanoant** [comment]
@dom96 It is important because:

1. Having shell script that is supposed to be executed, having Shebang but no execute bit set is freaking confusing for UNIX developers - because Shebang does not make sense without +x bit,

2. No projects I have seen require you explicitly pass build script to shell using `sh bootstrap.sh`.

3. It is inconsistent with other `*.sh` scripts that Nim & Koch produce which do have executable bit set.

4. Clicking `bootstrap.sh` without +x will not run from OS X or Linux file manager

**Comment by kirbyfan64** [comment]
It would be kind of funny if the executable bit disappears within an hour... ;)

**Comment by nanoant** [comment]
@kirbyfan64 Yeah, very special kind of funny :dizzy_face:

But what is actually funny is that, msys `bash` (aka msysGit Shell) shows `bootstrap.sh` as executable, because instead of using FS flag that do not exist on Windows, it check falls back to checking Shebang.

So currently Windows users working on `bash` have it working fine, where native UNIX users not.

**Pull request merged**
