### PR TITLE
Fix readPasswordFromStdin for Windows

### PR DESCRIPTION
**Pull request by def-**
I believe that's how it should be, would still appreciate someone with Windows to actually test it.

### CODE REVIEW

**Comment by dom96** [comment]
That depends on how the Linux version behaves. What is the output of this program?

```nimrod
import rdstdin
var pass = ""
readPasswordFromStdin("Password:", pass)
echo("Got pass: ", pass)
```

On Windows (with this patch) it is:

```
Password:Got pass: test
```

Without the patch:

```
Password:
Got pass: test
```

It is important to note that when the password is being typed in the cursor is on the next line. This should IMO not be the case, so this patch fixes that. But should ``\n`` be added after the password is typed in?

**Comment by def-** [comment]
Now it's the exact same behaviour as on Linux. I guess adding `\n` would be even better in most cases, but if someone wants no newline, they are still forced to have it. I'm still for adding it, so here we go.

I'm not sure how to detect EOF with the Windows version as well.

**Comment by Araq** [comment]
Adding a newline is un-nim-ic, please revert that.

**Comment by def-** [comment]
But it matches the behaviour of readLineFromStdin, no?

**Comment by Araq** [comment]
How so?

**Comment by def-** [comment]
When entering a line with `readLineFromStdin` the user will always terminate it with an enter, so there you get your newline.

**Comment by Araq** [comment]
ok, I misunderstood.

**Pull request merged**
