### PR TITLE
sorted & sortByIt

### PR DESCRIPTION
**Pull request by def-**
dom96 said we should care a bit more about functional programming before 1.0.

So I tried to reimplement the top example from here: http://www.vasinov.com/blog/16-months-of-functional-programming/

This is the final code:
```nim
import sequtils

type User = tuple[id: int, firstName, lastName: string, active: bool]

proc activeById(us: seq[User]): seq[string] =
  us.filterIt(it.active).sortedBy(it.id).mapIt(string, it.lastName)

let activeUsersById = activeById(@[
  (11, "Nick", "Smith", false),
  (89, "Ken", "Pratt", true),
  (23, "Jack", "Sparrow", true)
])

echo activeUsersById
```

If this code is actually wanted I can extend the documentation and add examples of usage.

It's also quite unfortunate that we even need the `mapIt` and related templates. Would be much nicer if instead we could do `.map(x => x.lastName)` instead of the more unwiedy `.map((x: User) -> string => x.lastName)`.

### CODE REVIEW

**Comment by oderwat** [comment]
I like it and I also think that Nim could attract a lot of people with some more functional programming coverage. Which in return may give Nim more coverage by them trying it. Something in the spirit of "Functional programming with Nim".

**Comment by dom96** [comment]
> Would be much nicer if instead we could do ``.map(x => x.lastName)`` instead of the more unwiedy ``.map((x: User) -> string => x.lastName)``.

This should be reported as an issue.

**Comment by flaviut** [comment]
`sortByIt`. "It" is what the collection is being sorted by, and for consistency it should be at the end.

**Comment by Araq** [comment]
I like it, but please add sortByIt to algorithm.nim, not sequtils.

**Pull request merged**
