### PR TITLE
Patch/csources as submodule

### PR DESCRIPTION
**Pull request by nanoant**
1. Solves a problem that updating Nim sources we have no indication we need to
   update csources as well.

2. Using submodule we can explicitly request that some Nim version requires
   some csources version to bootstrap.

3. `build.sh` now simply calls: `git submodule update --init --depth 1`
   instead shallow clone on missing csources subdirectory.

### CODE REVIEW

**Comment by dom96** [comment]
@Araq dislikes submodules so it's unlikely this will be merged unless he has changed his mind.

**Comment by nanoant** [comment]
@Araq asked for PR, so here it is. He may dislike submodules, but IMHO there is no better way to express bootstrap dependency than using Git submodule. And this is real problem, since simple `pull` on Nim's repo currently NOT update `csources` and will not give any indication for doing that. So build silently fails.

Also current `build.sh` always checks out newest `csources`, which makes compiling older Nim version probably fail in the future.

Anyway since we `build.sh` uses `--depth 1` it essentially does the same.

**Comment by kirbyfan64** [comment]
But now csources will get downloaded even if we don't want them. I like it the current way better.

Bootstrapping happens once. After that, we use the installed Nim to update itself.

`submodules` are so freaking easy to wreck.

**Comment by nanoant** [comment]
@kirbyfan64 Will be downloaded? By who, when? You need to explicitly use `git submodule update --init` to grab your submodules after pull. It won't happen automagically or you are neither forced to do so.

**Pull request merged**
