### PR TITLE
Test realtime GC, in a long running process via a shared object, without linking nimrtl.dll/so.

### PR DESCRIPTION
**Pull request by jpoirier**
As per a request from Araq. 

Includes a C and Nim coded client, Windows and Nix build files, and a readme. Thus far, only tested on a 64 bit Linux system. It'd be helpful if someone could test this on a Windows system, before merging, to make sure everything compiles properly via make.bat.

It's a first run, so input is welcome.

### CODE REVIEW

**Comment by flaviut** [comment]
The test suite already takes a very long time, I hope this test won't be turned on by default.

**Comment by jpoirier** [comment]
I wouldn't expect it too. 

I never really discussed any of the particulars with Araq and figured I'd just put something together and let the details get hashed out via pull-request comments.

**Comment by jpoirier** [comment]
The Nim client is already there, see below. I'll look into a special test section.

The test folder contains the following files:
- main.c  // a C client for shared.nim, it's a copy of main.nim
- main.nim  // a Nim client for shared.nim, it's a copy of main.c
- shared.nim  // the shared library 
- main.nim.cfg  // config file
- shared.nim.cfg  // config file
- Makefile  // builds shared.nim as well as the C and Nim client
- make.bat  // builds shared.nim as well as the C and Nim client

**Comment by Araq** [comment]
@def- or @reactormonk  can somebody incorporate this into our testing framework properly? I really want to merge this.

**Pull request closed without merging**
