### PR TITLE
Dropped 'T' from types, added 'deprecated' and updated code using those types

### PR DESCRIPTION
**Pull request by Perelandric**
This is the bulk of the changes for issue https://github.com/Araq/Nim/issues/2773. It builds and tests are currently running.

I have a good bit more to do in the `windows` library and I'll have a few questions before I continue but won't be able to get back to this until tomorrow.

### CODE REVIEW

**Comment by reactormonk** [comment]
Fair warning: Don't click on "files changed".

**Comment by Perelandric** [comment]
Some tests are failing, so I have some updating to do.

@reactormonk should I redo this as several smaller PRs or at least commits?

**Comment by reactormonk** [comment]
@Perelandric nah, just warning people. And some tests were failing before, run it both in devel and your branch and check testresults.html IIRC. Also, I can't run the tests at all, I get:

    tests/testament/nimcache/stdlib_typeinfo.c:585:2: error: unknown type name ‘GenericSeq’

I suppose you need to change some `TGenericSeq` magic to `GenericSeq`.

**Comment by kirbyfan64** [comment]
@reactormonk Unfortunately, I was curious and did not heed your advice. Apparently, that little GitHub loading symbol *can* freeze...

**Comment by Perelandric** [comment]
@reactormonk I had some issues with `TGenericSeq` so I reverted those changes. There were a couple others like that too. I must have missed one. It built for me though on 64-bit linux. I'll take another look.

**Comment by reactormonk** [comment]
@Perelandric compiler magic is very ugly to change. Maybe leave that out for now.

**Comment by Perelandric** [comment]
I'll tinker a bit but if I can't get it, I'll leave it to you guys.

**Comment by Perelandric** [comment]
Those last 3 commits are me just fumbling with git. I also had my PATH pointing to a different Nim install, so I think that was messing with me.

**Comment by dom96** [comment]
Thank you for changing all of these.

The amount of changes in this PR makes it rather difficult to review though. It might be a good idea to separate these changes into separate PRs.

**Comment by Perelandric** [comment]
@dom96 I can do that. Should I just close this one for now?

**Comment by dom96** [comment]
Yes please

**Comment by Perelandric** [comment]
@dom96 Just about to get back to this. I'm wondering how it's going to work with multiple PRs. Because I've also updated the code that uses the changed types, there isn't really a clean separation. Would it be better to do a single PR but broken up into multiple commits? Do you have any other ideas?

If it's a problem, I could start over and redo it all so that we can have cleanly separated PRs, but I'd like to avoid that if possible.

**Comment by reactormonk** [comment]
Start from the stdlib and then go down into system and the compiler.

**Comment by Perelandric** [comment]
@reactormonk Unless someone tells me otherwise, I'll do one PR with multiple commits so that the changes can be reviewed without freezing the browser.

In the files in the `windows` directory, there are many names that are ALLCAPS. Is there anything special about those? Should I keep them that way or should I CamelCase them?

Also, I'll have a short list of files where dropping the `T` would result in a naming conflict. I'll let you guys pick the proper names for those.

**Comment by dom96** [comment]
@Perelandric That should be fine. Keep the ``windows`` names as they are for now.

**Pull request closed without merging**
