### PR TITLE
compile nim on freebsd

### PR DESCRIPTION
**Pull request by dyu**
Thanks to http://forum.nim-lang.org/t/936 for showing how to fix the compile errors on freebsd.

### CODE REVIEW

**Comment by Araq** [comment]
Why not fix your OS instead?

**Comment by def-** [comment]
@dyu: Thanks for the fix. Don't mind Araq raging about everything Unix-related.

**Comment by Araq** [comment]
It's not about raging about everything Unix-related at all. If BSD's headers are broken, fix them, don't hack around in Nim.

**Comment by kirbyfan64** [comment]
I'm confused. `<sys/types.h>` is being included twice, and doesn't libdl still need to be linked in on non-BSD systems?

**Comment by kirbyfan64** [comment]
Nevermind. Ignore my last comment. I was tired...

**Pull request merged**
