### PR TITLE
fixes issue with CreateSymLink and CreateHardLink on Windows XP and less via conditional symbol

### PR DESCRIPTION
**Pull request by Leu-Gim**
`--define: winPreVista` should be added by user to his *nim.cfg* or command line. There's an alternative PR getting Windows version via `cmd /c ver`.

### CODE REVIEW

**Comment by dom96** [comment]
So if the user compiles with ``-d:winPreVista`` this will disable createSymLink/createHardLink? Are these not available pre-vista?

I think you should detect Vista at runtime instead using ``osinfo_win``.

**Comment by Leu-Gim** [comment]
*> So if the user compiles with -d:winPreVista this will disable createSymLink/createHardLink? Are these not available pre-vista?*

Yes, will disable, and CreateSymbolicLink is available from Vista, but I was mistaken about hardlinks, so now only symbolic links are under `when`.

About `osinfo_win` - it doesn't compile for me, C-compiler fails (MinGW) with `stdlib_osinfo_win.c:493:32: error: request for member 'ClEnv' in something not a structure or union`,
the same for `ClPrc`, in `getproductinfo`. And it would require more changes in code. With just one advantage - one could compile his program once and distribute binaries for any Windows. Some kind of symlinks to directories only  - [junctions](http://www.flexhex.com/docs/articles/hard-links.phtml) - exists for WinXP, but there's no single API function for it. Maybe it should be implemented in `winlean`?

**Comment by dom96** [comment]
I don't see why this is necessary. If the programmer cares about supporting earlier versions then they simply won't use createSymLink/createHardLink.

**Comment by Araq** [comment]
Move these symlink procs to a new symlinks module and call it a day please. I don't want them in os.nim really anyway, symlinks suck.

**Comment by dom96** [comment]
I really don't see why this is necessary at all. Like I said multiple times, deadCodeElim should take care of it. @Araq no?

**Comment by Araq** [comment]
@dom96 true.

**Pull request closed without merging**
