### PR TITLE
Commit OS X Framework declarations for Nim.

### PR DESCRIPTION
**Pull request by philip-wernersbach**
Thanks to Nim's support for C and Objective-C FFI, Nim can wrap OS X's system frameworks. This commit adds stub files for the system frameworks that come with every OS X installation. The whole point of these is to abstract away the linker flags and header locations for each framework.

### CODE REVIEW

**Comment by reactormonk** [comment]
Any reason this should go to the stdlib over a nimble package?

**Comment by oderwat** [comment]
There is "/lib/windows" ;-)

Actually I think the "abstraction" is not very important here, as it is always the same pattern for the frameworks:

```
{.passL: "-framework vImage".}
const VIMAGE_FRAMEWORK_HEADER* = "<vImage/vImage.h>"
```

I guess that could probably expressed as an template: `osxframework vImage` which takes the name and puts it into place (not sure if that works though).

So I think it would be cool to have `/lib/osx/` but not for a bunch of files which are boilerplate style definitions.

**Comment by reactormonk** [comment]
So we need more macros here?

**Comment by philip-wernersbach** [comment]
I was originally going to dump these into a nimble package, but I reconsidered. These are OS X system libraries that are needed to access certain features of OS X. If Nim gains traction for serious OS X programming, then those programs would depend on a good amount of these libraries. It seems silly to keep something like that out of the standard library.

Foundation is the runtime library for Objective-C on OS X. On OS X a Nim program that uses Objective-C FFI won't link without linking Foundation, and won't compile without including the Foundation header.

I do think there is a case to be made for keeping the frameworks that are closer to the core OS in the standard library and keeping the frameworks that are farther from the core OS in a nimble package. OS X is weird though in that the ecosystem is really a part of the operating system. For instance, Cocoa is the de facto standard for GUI applications on OS X and it's shipped with OS X. Would this go in the standard library or the nimble package? That would be the arbitrary question here.

From a practical standpoint I like @oderwat's suggestion for something like `importframework` instead of these stubs. That's weird to me though, as we don't have to do `importunixlibrary pthreads` or `importunixlibrary c++runtime` on other platforms.

**Comment by oderwat** [comment]
I don't see a problem with adding this macro to `/lib/osx`. Actually I feel this is very convenient:

```nimrod
import macros, strutils

macro osxFramework*(s: string): stmt =
    result = parseStmt(("{.passL: \"-framework $1\".}\n" &
        "const $2_FRAMEWORK_HEADER* = \"<$1/$1.h>\"") %
        [s.strVal,s.strVal.toUpper()])
```

and then write:

```nimrod
import osx
osxFramework("Cocoa")
osxFramework("CoreData")
```

I just hacked that together but looks to me as if that would work. We could omit adding >100 files which most(?) users don't need. Afaik using the linux or windows includes does not need to include them all somewhere in the libraries of Nim?

**Comment by Araq** [comment]
The linux and windows modules are mostly a historical artifact, nothing to copy for macosx. Windows.nim in particular is way too big and should be a separate Nimble package. Wether you think it belongs to the core or not is debatable, but our policy is nothing goes into the core that we don't want to maintain. And we don't want to maintain excessive wrappers nor stubs for macosx.

**Comment by Varriount** [comment]
Just to be clear, on Windows 'winlean.nim' is the file is used by the standard library for access to the Windows API, not 'windows.nim' . Entries from 'windows.nim' are checked and moved over to 'winlean.nim' on a case by case basis, as they are used by the stdlib. (Yes there are a few instances where 'windows.nim' is used by stdlib modules, but those should really be modified to use 'winlean.nim', and don't reflect current policy)

**Pull request closed without merging**
