### PR TITLE
Add and switch to a flat svg logo on website

### PR DESCRIPTION
**Pull request by josephwecker**
Graphic design should never be done by committee and always risks the most "bike-shedding." So rather than talking about it, I humbly submit a more clean and modern logo for nim. It is also fully in vector format (svg) for simplified use in other assets and derived work etc.

screen-shot-alternate-nim-logo

### CODE REVIEW

**Comment by dom96** [comment]
Looks good. Not too sure about the grey on the inside of the crown though, but all I can think of to make it look nicer is perhaps a dark golden colour? 

Would it make sense to make the rest of the website flat too?

**Comment by josephwecker** [comment]
After sleeping on it, I agree completely. The difficulty is that dark-golden == brown. But it does look more coherent now:
screen shot 2015-05-17 at 8 28 27 am

Regarding the rest of the website- yes, there's lots that can be done (like with anything) to clarify, simplify, and strengthen. I think that it can be done incrementally though- the website has a good feel and is quite functional & informative. It was just influenced a *little* too much by what looks like video-game-menu-screen design and older web design. (in fact, roughly 2006 web design according to [this](http://www.templatemonster.com/infographics/web-design-trends-years-2004-2014.php) ). Next step I would like to try is remove or lessen some of the glows etc.- especially the ones that look poor on retina & high density displays. But, again, I think it can be done incrementally, and I'm sure it can be done in a way that strengthens the site and doesn't diminish its existing chic.

**Comment by dom96** [comment]
It would be brilliant if you could do that. But we should consult @PhilipWitte who created the current design.

@PhilipWitte let us know what you think.

**Comment by PhilipWitte** [comment]
@dom96, @josephwecker : I'm glad to see more designers in the Nim community. That said, I completely disagree that your logo and simplifying the website's 'shine' and 'gradient' are good visual directions. I think my logo looks much more.. rewarding? (like you just found a shiny coin, rather than stumbled upon a business), and is significantly more attention grabbing (partially do to the color choice.. 'shining white' will steal more focus than 2 shades of orange pulled from other parts of the website). I think getting people to focus on the name 'nim' is good thing because Nim is still relatively young and unknown. The flat look feels out of place in comparison to the rest of the website too, IMO. But this isn't my decision, of course, and it should go without saying that my opinion as the original designer is biased.

Also, I think making the logo SVG is kinda pointless, considering it never scales and source SVG is already on github for people to use for branding (including simplified and iconic versions). An image allows you to use more visual effects and probably renders faster anyways.

That said, I completely agree that some places of the site are not ideal. Namely, the carousel greeter was a bad design for a programming website. I highly doubt anyone actually sees all the code examples there. Fixing this should be pretty easy.. just replace the rolling examples with small static snippets and a link to find more simple snippet examples.

Another thing is that we could use intelligent liquid layout in the future to scale a broader range or devices and make full use of screen space.. but honestly the site doesn't really have enough text/content to justify that design.. which is why I made it a simple column layout.

----

If @Araq and the community prefer @josephwecker's design, I would suggest tweaking the colors a bit (make it grab more focus) and increasing the crown size a bit (it's a little too small compared to the 'nim' part IMO).

I'm sorry to sound overly critical. I'm proud or my design, but I welcome change and improvement as well.. I just don't think this is it. At least, not without a complete site re-design (the flat look would work better with a flatter website).

**Comment by josephwecker** [comment]
Thanks @PhilipWitte - you deserve to be proud of the design. And it looks like a lot of time and thought went into it. I purposefully chose to try an alternative to only one piece of the assets because I didn't know if I'd be stepping on someone's toes (yours apparently- sorry!) Some quick points and then I'll butt out unless this happens to move forward at all (design flame-wars are much worse than technical ones because there is a great deal of subjectivity and also because sometimes it takes a lot of time before you know if certain aspects of a design really work even for a professional):

* SVG makes a *huge* difference on high density displays. Unfortunately it's not something that can be conveyed with screenshots. Suffice it to say that the png makes everything look extremely pixilated and old.

* I couldn't find the svg assets you mentioned except for an outline of the crown. I probably didn't look hard enough.

* While the website does have design elements that look very outdated for the web, I realize they are still used a lot in video-game user interfaces, and I recognize that video game designers (and related) are kind of a core user of Nim at the moment.

* With that said, the designs that I find compelling (esp. for language sites) are minimalistic- possibly too minimalist for some tastes. I find the aesthetics of [haskell's](https://www.haskell.org/), [elixir's](http://elixir-lang.org/), or [node.js's](https://nodejs.org/) sites appealing. On the other hand, I find, for example, [Julia's](http://julialang.org/) or [perl's](https://www.perl.org/) *too* minimalistic. Not arguing that there is something perfect out there- just letting you know what direction I'm coming from :-)

Anyway, I hope you take all that in the spirit it's intended and that it didn't come across as diminishing your contribution. With code, as I'm sure you know, almost anything you write, if its remotely useful, ends up getting rewritten and changed, so that eventually very few actual lines of code are yours, yet in a way its all still yours- your vision etc.

**Comment by PhilipWitte** [comment]
@josephwecker Ah, thanks for being so considerate, I didn't mean to come off as offended (I'm not). This conversation (ie, people saying the website is too 'shiny') has been brought up on the IRC before, with supporters on both sides. I want to stress that I'm all for Nim growing beyond my initial visual/web design, and I applaud any and all design submission to improve that work (including this one. Thank you for taking the time to actually make a logo proposal you feel is an improvement). I agree completely that communities grow and evolve, and that implies change in all places.

However, I still feel that gradients and visual candy are nice (regardless of the latest fashion rating), and while I agree that these things are very subjective, that doesn't mean we can't make objective design choices. If peoples opinions differ we need to measure them and cater to the mass. If a simpler/flatter website would help Nim reach more people, it only makes sense to move that direction.

Even if that is the case (we also need @Araq's opinion), I would ague against doing it one piece at a time. We'll end up with a hodgepodge design halfway between anyone's preferences. It would be better to come up with a new web/forum design to match the logo change (again, visual proposals here are very welcome).

One last thing before I address your points, the visual changes are rather recent (they changed with the rename), and I am weary from a marketing standpoint about changing the logo, specifically, too much so close to that (not that your design is very far off). We noticed a significant boost of users with the name change, and while I think that was mostly due to the name change itself and other factors (like the new release and a couple of excellent articles published in sync) I like to think it was also partially due to the visual face-lift of the logo, web, and forums (which now has significantly more traffic than before, probably due to the website including it in the main nav, and the more polished visuals). I would hate to disrupt that, so I think whatever changes made should be backed up with lots of community votes.

About your points:

- Interesting.. I don't have a HiDPI display and didn't realize that. Although technically doubling the image resolution would fix this? I'm guessing this could be addressed with CSS that chooses HiDPI images when appropriate. Of course, I agree if a simple logo is the direction then SVG makes more sense than an image.

- The logo's are here: https://github.com/nim-lang/assets/tree/master/Art
Note that you'll need Inkscape to properly view some of the SVGs (cause that's what they where made with).

- I'm not sure "current fashion trend" is the best argument for change. And perhaps the design does reach out to game devs more than others, but I'm not sure that's true, or even a bad thing.

- Yes I like Haskell's and Node.js's design more than Nim's current site (not Elixir's so much). But the core difference between these is not so much the graphics/effects as the content organization. The text content and link structure of the existing site is mostly a hold-over from the original site (the one before my first design, before the current design). This is the main culprit. We should really design a new site around reorganized content (two column layout like Haskell's), and come up with a core nim example (and an examples page). The home-page content is tl;dr to properly convey an overview of Nim's key features (even though reading some of it's bullet points is what initially led me to try Nim in the first place). Unfortunately I don't realistically have to much time to help with that endeavor right now.

**Comment by kirbyfan64** [comment]
Isn't Python's web site a tad bit stylistically like Nim's? e.g. the carousel.

**Comment by josephwecker** [comment]
This is good context that I didn't have- thanks @PhilipWitte. That's essentially why I decided to do a single discrete change as a PR- I knew I didn't really have all the context of recent changes and discussions- at the same time I wanted to be constructive and not just another random opinion :-)

If you just came out of a whole bunch of recent design work and I assume all the exhausting bike-shed-painting discussions that went along with it I can completely understand letting things sit and settle in for a while longer- maybe to accompany a significant release etc. I'm also grateful that you took the time to respond given the recent work :-)

There are design elements that transcend trends, and in new mediums & contexts it takes many cycles of trend to tease them out- just like in coding. I didn't mean to imply that blindly following recent trends is intrinsically a good thing- just that blindly following trends from a few years ago is almost certainly not a good thing. But it's a minor point that only applies in some trivial ways here.

I actually like the carousel in concept- I can't stand trying to look into a language and digging for the actual code. By the way: site I always found extremely functional and aesthetically adequate: [slim](http://slim-lang.com/)

Aaaaanyway- I'll be happy to experiment with some changes to the logo here according to your earlier feedback if there's interest in moving forward now, and I also won't be offended if this gets tabled for now (although I may try to propose something like it in for the PDF manuals etc. later ;-)  Finally, I'd be happy to help with a more thorough changeset now or later.

**Comment by reactormonk** [comment]
@josephwecker I love the part about slim where they have a lot of space for code. IMO something similar for nim would be great.

I'm not sure if we wanna discuss design here or on the nim forum.

**Comment by josephwecker** [comment]
@reactormonk yeah, it's effectively a cheat-sheet for the most commonly used pieces (which would probably be infeasible for Nim, but it's still a good example of striking a very good balance between easing a new user in while being very functional for all users.)

**Comment by Araq** [comment]
Well we need a completely new and more boring design for version 1, so that people take it more seriously. But IMHO the current design is simply ahead of its time, fitting Nim quite well. ;-)

**Comment by josephwecker** [comment]
Well put, @Araq.

Awesome, ok. Thanks everyone (esp. @PhilipWitte) for the feedback. I'm going to close this now- time to get back to 'real' work ;-)  I might try to do a PR for more minor changes (like fixing some resolutions for retina displays etc.) later, and this flat & slightly stylized logo will still be in the 'new-logo' branch of my copy of the repo for the future if we need it when we're closer to 1.0 and ready to have that discussion via the forum.

**Comment by dom96** [comment]
@josephwecker Could you create a PR for the assets repo that @PhilipWitte linked a while back with your new logo? I think it looks quite nice and I'm sure others may find it useful when wanting to advertise Nim :)

**Comment by josephwecker** [comment]
@dom96 will do

**Comment by josephwecker** [comment]
@dom96 https://github.com/nim-lang/assets/pull/2

**Comment by PhilipWitte** [comment]
@josephwecker, @dom96, @Araq: The more I look at this logo side-by-side with the existing one (compare [this](https://github.com/nim-lang/assets/blob/master/Experimental/logo-simplified.svg) to [this](https://github.com/nim-lang/assets/blob/d06b005c3d56536e1f86913d12cdf8da6c1a89aa/Art/logo-withBackground.png)) the more I like what @josephwecker has done with the overall vector shape and simplification of the logo using negative space (especially compared to the [existing](https://github.com/nim-lang/assets/blob/d06b005c3d56536e1f86913d12cdf8da6c1a89aa/Art/logo-monochrome-black.png) 'iconic' logo). I still don't think it fits into the current site, and don't think we should just swap out the logos willy-nilly, but I think the next version of the site should definitely use some version of his logo.

@josephwecker: I would like to encourage you to continue making designs and to post them on the forums. We need as much community feedback (and designer work) as possible going forward, and it would be great if we could come up with a new website design for the 1.0 release using your logo and new graphics/site-layout to match it.

**Comment by josephwecker** [comment]
@PhilipWitte: Great! I'll be happy to help. I'll just issue PRs to assets/Experimental for the most part and link to them in the forum for feedback.

**Comment by ozra** [comment]
I'll tell you my personal impressions as a "freshman nim interestee", just for kicks:
My first impression when finding the site after googling "this mysterious thing I've heard about", was that "this is a hobbyist language, no point to look any further, looks like a video game cross body building supplement ad from the nineties". But, at the same time it made it feel unique and un-compromizing. 
I think that flat crown with a in-between-the-grey-and-dark-gold is real nice. As for the 'nim' that actually works with the shiny-metal-half-glow. As for the rest, no doubt there's too much shine. What should be the focus is of course the language. And obviously, as already stated, a plainer not so intrusive/designed, eh.. design, would compliment the information at heart when 1.0 is reached.

I could see the crown get replace already now! The white crown takes over the whole site, and imo, WTF has a crown to do hogging the entire attention span? Yeah, I know it was called Nimrod before, but..

And, _possibly obvious, but_: this is not a dis, the design _is_ really fucking cool - it's just that - information / code centric presentations needs a _less_ cool design! One of those places where Yngwie Malmsteens 'more is more' don't fit the bill ;)

**Pull request closed without merging**
