### PR TITLE
Add format string function using micro DSL.

### PR DESCRIPTION
**Pull request by hiteshjasani**
Added function to enable easy formatting of strings.
* Left or right justify strings within a specified width
* Use any padding character, defaults to space
* Truncate string from left or right side if larger than specified width
* micro DSL wrapper function provides a more terse interface

For example:

```nim
assert fmt("<5<", "abc", '.') = "abc.."
assert fmt(">5<", "abc", '.') = "..abc"
```

### CODE REVIEW

**Comment by gradha** [comment]
Maybe these changes would be better placed in the already existing [subexes module](http://nim-lang.org/subexes.html) which also implements a micro DSL?

**Comment by def-** [comment]
This looks similar to functionality in the strfmt module: http://lyro.bitbucket.org/strfmt/

**Comment by Varriount** [comment]
@hiteshjasani What does this add over existing functionality?

**Comment by hiteshjasani** [comment]
I found myself missing `printf` in Nim and imported `c_printf` into a number of mini projects.  I don't know the reasoning why `printf` usage seems to be considered taboo, but it is sorely missed.  Secondly, I think that languages which are trying to attract new users need to have some polishing to ensure they can easily use the new tools.  A system programming language like Nim needs an easy way to display formatted text.

Here's a sample bit of code that I whipped up.  Using the patch I submitted, I find it easy to display the formatted text - adhering to length restrictions on columns and use left or right truncation.

```nim
import strutils                                                                                                                                                 
                                                                                                                                                                
type Data = tuple[name: string, age: int, weight: float, description: string]                                                                                   
                                                                                                                                                                
when isMainModule:                                                                                                                                              
  let d: seq[Data] = @[                                                                                                                                         
    ("sam", 21, 180.87, "likes to drink beer"),                                                                                                                 
    ("wendy", 21, 110.2, "loves to sing in the shower"),                                                                                                        
    ("matt foley", 35, 220.5, "lives in a van down by the river")]                                                                                              
                                                                                                                                                                
  echo "\nRaw dataset"                                                                                                                                          
  for x in d:                                                                                                                                                   
    echo x                                                                                                                                                      
                                                                                                                                                                
  # formatted output                                                                                                                                            
  echo "\nFormatted printing of dataset\n"                                                                                                                      
  let                                                                                                                                                           
    nf = "<6>"    # name format                                                                                                                                 
    af = ">5>"    # age format                                                                                                                                  
    wf = ">8<"    # weight format                                                                                                                               
    df = ">20<"   # description format                                                                                                                          
    sep = "-----------------------------------------"                                                                                                           
                                                                                                                                                                
  echo nf.fmt("Name") & " " & af.fmt("Age") & " " & wf.fmt("Weight") & " " &                                                                                    
    df.fmt("Description")                                                                                                                                       
  echo nf.fmt(sep) & " " & af.fmt(sep) & " " & wf.fmt(sep) & " " & df.fmt(sep)                                                                                  
  for x in d:                                                                                                                                                   
    echo nf.fmt(x.name) & " " & af.fmt($x.age) & " " &                                                                                                          
      wf.fmt(formatFloat(x.weight, ffDecimal, 1)) & " " & df.fmt(x.description)                                                                                 
                                                                                                                                                                
  echo ""      
```

It displays the following:

```
Raw dataset
(name: sam, age: 21, weight: 180.87, description: likes to drink beer)
(name: wendy, age: 21, weight: 110.2, description: loves to sing in the shower)
(name: matt foley, age: 35, weight: 220.5, description: lives in a van down by the river)

Formatted printing of dataset

Name     Age   Weight          Description
------ ----- -------- --------------------
sam       21    180.9  likes to drink beer
wendy     21    110.2 o sing in the shower
matt f    35    220.5 an down by the river
```

One thing I especially like about this solution is that the column formats work for formatting the titles, the separator bar and the data values.

Summary:
* Can this same thing be easily accomplished using current Nim libraries?  I don't know, but I didn't run across something equivalent.  If there is something there that I missed, then maybe there's an opportunity to improve the documentation.
* What about the strfmt that @def- pointed out?  That library looks interesting and would be a good addition to Nim.
* What about this going into the `subexes` module?  I this solves a different needs and possibly fits better with `strutils`
* Easy formatting of text is, in my humble opinion, a core need in any mainstream programming language.  If people feel that there is some other code that should be in the stdlib rather than what I've submitted, that's fine with me -- as long as there is *something* in the stdlib that makes formatting text simple.

**Comment by hiteshjasani** [comment]
Played around with my sample code and leveraged the `formatstr` function.  This is a cleaner example.

```nim
import strutils                                                                                                                                                 
                                                                                                                                                                
type Data = tuple[name: string, age: int, weight: float, description: string]                                                                                   
                                                                                                                                                                
proc line(n, a, w, d: string) =                                                                                                                                 
  let                                                                                                                                                           
    text = "$1  $2  $3  $4"                                                                                                                                     
    nf = "<6>"    # name format                                                                                                                                 
    af = ">5>"    # age format                                                                                                                                  
    wf = ">8<"    # weight format                                                                                                                               
    df = ">20<"   # description format                                                                                                                          
  echo text % [nf.fmt(n), af.fmt(a), wf.fmt(w), df.fmt(d)]                                                                                                      
                                                                                                                                                                
when isMainModule:                                                                                                                                              
  let d: seq[Data] = @[                                                                                                                                         
    ("sam", 21, 180.87, "likes to drink beer"),                                                                                                                 
    ("wendy", 21, 110.2, "loves to sing in the shower"),                                                                                                        
    ("matt foley", 35, 220.5, "lives in a van down by the river")]                                                                                              
                                                                                                                                                                
  echo "\nRaw dataset"                                                                                                                                          
  for x in d:                                                                                                                                                   
    echo x                                                                                                                                                      
                                                                                                                                                                
  # formatted output                                                                                                                                            
  echo "\nFormatted printing of dataset\n"                                                                                                                      
  let sep = "-----------------------------------------"                                                                                                         
                                                                                                                                                                
  line("Name", "Age", "Weight", "Description")                                                                                                                  
  line(sep, sep, sep, sep)                                                                                                                                      
  for x in d:                                                                                                                                                   
    line(x.name, $x.age, formatFloat(x.weight, ffDecimal, 1), x.description)                                                                                    
                                                                                                                                                                
  echo ""
```

**Pull request closed without merging**
