### PR TITLE
Fixes #2584

### LINKED ISSUE #2584: Bad error message when trying to construct an object incorrectly
```
type Foo = object
  a: int
  b: float

discard Foo(1, 1.5)
```

This should produce an error message saying that `Foo` is a type and you should initialize it like `Foo(a: 1, b: 1.5)`.

The actual error message is: `badmsg.nim(5, 11) Error: undeclared identifier: 'Foo'`

### PR DESCRIPTION
**Pull request by dom96**
Better compiler errors for accessing undeclared fields, calling undeclared
procedures <del>and procedure fields</del>

### CODE REVIEW

**Comment by reactormonk** [comment]
What is a "procedure field"?

**Comment by dom96** [comment]
Hrm. Perhaps that's not the best name for it.

**Comment by dom96** [comment]
I removed it.

**Comment by Araq** [comment]
"undeclared procedure"? the Lang uses 'proc'. Instead perhaps use "routine", this is the more abstract term, covering also converter, method etc.

**Comment by dom96** [comment]
Done.

**Comment by dom96** [comment]
Oh, forgot to update the tests.

**Comment by dom96** [comment]
And done.

**Pull request merged**
