### PR TITLE
Rename *.nimrod.cfg to *.nim.cfg

### PR DESCRIPTION
**Pull request by def-**

### CODE REVIEW

**Comment by gradha** [comment]
Might be a good idea to accept or reject https://github.com/Araq/Nim/issues/1555 while you are at it.

**Comment by reactormonk** [comment]
Does the compiler already read both?

**Comment by def-** [comment]
Judging from my experiments and this code, yes: https://github.com/Araq/Nim/blob/devel/compiler/nimconf.nim#L249-L251

**Comment by Araq** [comment]
@def- Please make the compiler also accept ``.nimcfg`` and warn about ``nimrod.cfg`` files.

**Pull request merged**
