### PR TITLE
Add procs for VirtualAllocEx and VirtualFreeEx in windows.nim

### PR DESCRIPTION
**Pull request by chrisheller**
These are the out of process equivalents of VirtualAlloc and VirtualFree.  Tested on 32 bit and 64 bit environments.

### CODE REVIEW

**Comment by reactormonk** [comment]
Are `SIZE_T` and `DWORD` equivalent? The signature of `VirtualAllocEx` has `SIZE_T` in the third slot. https://msdn.microsoft.com/en-us/library/windows/desktop/aa366890(v=vs.85).aspx

**Comment by chrisheller** [comment]
Good catch.  I just looked and both VirtualAlloc and VirtualAllocEx have SIZE_T and not DWORD as the parameter type,  so the original code needs to be adjusted as well.  I'll do that now.

**Comment by chrisheller** [comment]
I updated a few more places in the memory management procs where MSDN showed that the size should be a SIZE_T instead of a DWORD.

**Comment by reactormonk** [comment]
Could you duplicate the old ones and mark them with `{.deprecated.}` so we don't break code? E.g.

    proc GlobalAlloc*(uFlags: int32, dwBytes: DWORD): HGLOBAL
        {.stdcall, dynlib: "kernel32", importc: "GlobalAlloc", deprecated.}

**Comment by chrisheller** [comment]
I updated the procs where there was a parameter that was switched from DWORD to SIZE_T,  but there are two (GlobalSize and HeapSize) that had the return type changed.   

Should I wrap those in "when defined(cpu64)" for the SIZE_T returns and have the else return DWORD as before?  That would keep 32 bit code working without change (since DWORD is correct for 32 bit),  but that would then force someone targeting 32 and 64 bit code to do the same wrapping, which seems a bit ugly. 

Any other ideas for this?

**Comment by reactormonk** [comment]
I'd just let it burn. Can't have everything.

**Pull request merged**
