### PR TITLE
Add UTF8 string conversions to uppercase and to lowercase

### PR DESCRIPTION
**Pull request by ivoras**
A standard library should have basic Unicode uppercase / lowercase conversion procs.

### CODE REVIEW

**Comment by Araq** [comment]
First of all, the names don't adhere to our style guide. Secondly, why do we need these? toUpper or toLower for unicode is almost always a mistake, instead the *comparison* should ignore case.

**Comment by ivoras** [comment]
Well, while I totally agree that you might have a personal conviction that toUpper or toLower for unicode strings is almost always a mistake, I invite you to consider that every single practical unicode-aware language has them (and it also goes with the "batteries included" idea of e.g. Python). For example, [Go](https://golang.org/pkg/strings/#ToLower), [D](http://dlang.org/phobos/std_uni.html#toLower) and [Rust](http://doc.rust-lang.org/1.0.0-beta.4/std/primitive.str.html#method.to_lowercase) are considering it useful.

Since Nim already has toUpper / toLower for Runes, not having them for strings simply means more work for developers in making their own personal utility libraries for such trivial things.

I've myself used it today to test if a string has already been seen, and since I want it to be efficient on millions of strings, I've put them in a hash set.

As for naming, the [document Google finds](https://github.com/Araq/Nim/wiki/Style-Guide-for-Nim-Code) does not specify correct naming nor what to do when a part of the name is an acronym / initialism. The same file (unicode.nim) contains both "Utf8" and "UTF8" inside proc names, and the comments mix between "UTF8" and "UTF-8". I'm fine with whatever naming choice you decide. 

What are you thinking?

**Comment by reactormonk** [comment]
Just call it `toLower` and `toUpper`, prefixing is already done by the module itself if needed. Otherwise we have overloading for that one.

Could you also add a case-insensitive compare?

**Comment by maxgrenderjones** [comment]
If strings gain semantic functions (even as simple as swapping `a-z` for `A-Z`), don't they need to know what encoding is being used? Or does string need to be defined as using `utf8` for internal storage? (In other words I sympathise with having `utf8` either in the function name or having an encoding parameter which would default to `utf8`)

**Comment by ivoras** [comment]
You are right, since the documentation already states that "strings are assumed to be in UTF-8", there's no need for a prefix in the function names.

Should I make another pull request or will you simply delete the prefix before committing?

**Comment by Araq** [comment]
Well here is the thing: Many projects import unicode, strutils.  If unicode.toUpper suddenly exists it forces the programmer to make a concious choice which proc to call. So that does break backwards compatibility but you can argue that it's for the better. IMHO I would name them ``toUpperRunes`` and ``toLowerRunes`` for this reason, but I won't use my dictatorship superpowers, so vote away.

**Comment by kirbyfan64** [comment]
+1 to `*Runes`.

**Comment by dom96** [comment]
:+1: for ``toUpperRunes``/``toLowerRunes``

**Comment by ivoras** [comment]
toUpperRunes(), but it operates on a string? It seems like a warty name.

And it doesn't seem right to make a function which operates on a seq of runes or something like that, since the point is to make it work on strings...

**Comment by dom96** [comment]
Perhaps ``toUpperUnicode``/``toLowerUnicode`` would be better?

**Comment by jochenvdv** [comment]
:+1: for the Unicode suffix instead of Runes

**Comment by maxgrenderjones** [comment]
Me too on `toXxxUnicode`, since we're not talking about runes, but the unicode representation of them.

Also on thinking more about an `encoding` parameter/suffix, I think the documentation saying that it assumes all strings are in `utf8` already implies that all bets are off if you call a semantic method and your string is in another encoding, so don't think we need to have `toUpperUTF8` (or however you like to capitalise things - thank the stars Nim at least doesn't care!). However we should leave the door open to passing an encoding parameter into semantic methods at some point in the future

**Comment by ivoras** [comment]
Actually, the "magic" of everything working as expected when including the unicode module is nice. It requires a conscious decision by the programmer and it means less code will need to be changed when adding unicode features. Since in normal cases ASCII is a subset of UTF-8, all common usages will also work if toUpper / toLower suddenly work with UTF-8.

There remain edge cases when toUpper / toLower is passed binary garbage, but I don't think that should influence the library design. GIGO.

Anyway, this has become a bikeshed and I won't participate. The 8 lines of code I've submitted are yours to commit or modify.

**Pull request closed without merging**
