### PR TITLE
Add system.indices

### PR DESCRIPTION
**Pull request by def-**
I find this useful since I often iterate from low to high, but don't want to use `for index, value in list` when I don't need the value.

The template is pretty simple:
```nimrod
template indices*(x): expr = low(x) .. high(x)
```

I'm not sure about the name. `range` would be perfect, but is taken already, `indices` (my favorite) is analog to `items` and `pairs`. Altenative choices are `span` and `space`.

This could be done with an iterator:
```nimrod
iterator indices(x) =
  for i in low(x) .. high(x):
    yield i
```
But then you can't create ranges:
```nimrod
var r = indices(x)
```

If you want to iterate over datatypes the values could be converted to `BiggestInteger` in the template, which I didn't do since `low` and `high` don't do that either.

### CODE REVIEW

**Comment by Araq** [comment]
'system.mitems' is much more important.

**Comment by dom96** [comment]
:+1:

**Comment by def-** [comment]
Well, I tried to make mitems but ran into problems: https://github.com/Araq/Nim/issues/1833

**Comment by reactormonk** [comment]
Scrap up a test and we'll plug it in.

**Comment by def-** [comment]
> Scrap up a test and we'll plug it in.

Nice, done.

**Comment by MasonMcGill** [comment]
Hey; this looks convenient, but it introduces very unintuitive behavior when used with any library that provides matrices/multidimensional arrays. Also, `indices` isn't a name I'd love to have reserved by `sytem.nim` (if I pull this commit, I'll have to go change quite a bit of code). If you wouldn't mind, would you consider either

- Constraining the arguments `indices` can accept (e.g. `array|openarray|seq`)?
- Moving `indices` to another module.

**Comment by def-** [comment]
Collisions are unfortunate. I realize the name is very general.

> Constraining the arguments indices can accept (e.g. array|openarray|seq)?

I don't like this, because it should work with everything that provides `low` and `high`. Could use a typeclass for that, once they're stable enough. Would that work?

**Comment by MasonMcGill** [comment]
This does seem like a good use-case for typeclasses, though `low` and `high` are currently on the Nim manual's list of nonoverloadable builtins, so I'm not sure you're supposed to overload them. If you're not, then maybe `seq|array|openarray` covers all your bases.

Either way, it would be nice if the argument was constrained somehow. It's not a huge deal; I'm just not too excited about having to fix code because something new popped up in `system.nim` : )

**Comment by Araq** [comment]
I'm closing this: It causes trouble for at least Mason and this "everything should be in system for convenience" has to stop.

**Pull request closed without merging**
