### PR TITLE
Fixes #1962

### LINKED ISSUE #1962: httpclient.HttpMethod should not be an enum
Hi,

HttpMethod is currently defined as an enum. This actually doesn't correctly model the method as defined by the HTTP spec: the method can be one of the values listed in the enum, ''or'' an extension method: http://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html

As a practical example, having HttpMethod defined as an enum breaks being able to use httpclient to implement a WebDAV client (since there is no way to issue COPY, LOCK, MOVE, etc).

I would suggest changing the type to a string, which would allow for WebDAV (and whatever other extension methods) to specify the method as needed.

### PR DESCRIPTION
**Pull request by Varriount**
Fixes #1962

### CODE REVIEW

**Comment by flaviut** [comment]
I'd separate code formatting and fixes into separate commits, but I suppose that's not a big deal.

**Comment by dom96** [comment]
Nice! Please add docs to the procedures you added. You can just copy and paste most of the docs from the other request procs but add an explanation of the format of ``httpMethod``.

**Comment by Varriount** [comment]
@dom96 Are the new doc-comments ok?

**Comment by dom96** [comment]
Good enough I suppose.

**Pull request merged**
