### PR TITLE
Fix parallel build on FreeBSD

### PR DESCRIPTION
**Pull request by modk**
This fixes the parallel build problem on FreeBSD and should not affect Linux builds. 
The problem was that FreeBSD's `waitpid()` changes its second parameter `status` even if the waited-for proccess has not exited, while Linux's doesn't. The nim compiler expects this parameter to be unchanged except when the process has ended.
I added a check `WIFEXITED` that is imported from `<sys/wait.h>` and changed the corresponding C imports.
I was not able to test this thoroughly under Linux as I currently only have an ancient VM image, but firsts tests showed no problems.

### CODE REVIEW

**Comment by def-** [comment]
Fails to bootstrap on Linux at linking:

```
[...]
CC: compiler_passaux
CC: compiler_depends
CC: compiler_docgen2
CC: compiler_service
CC: compiler_modules
[Linking]
compiler/nimcache/compiler_jsgen.o: In function `newproc_602207.constprop.20':
compiler_jsgen.c:(.text+0x1d3): undefined reference to `gch_47244'
compiler_jsgen.c:(.text+0x1d8): undefined reference to `addzct_48817'
[...]
compiler_main.c:(.text+0x1ab8): undefined reference to `myprocess_614062'
compiler_main.c:(.text+0x1ac4): undefined reference to `myclose_614197'
collect2: error: ld returned 1 exit status
Error: execution of an external program failed
FAILURE
```

**Comment by Araq** [comment]
Please make this code BSD specific. It's just not worth taking the risk it breaking on other "Posix-like" systems.

**Comment by modk** [comment]
After extensive discussion on IRC and fixing a silly mistake it should build/bootstrap now on Linux again. Can anybody still test it on Mac?

**Comment by def-** [comment]
I can confirm that it works on Linux now (and I finally understand why).

**Comment by Araq** [comment]
We don't want to test on Mac. Or embedded Linux with µlibc. Or SurrealLinux version 3.14 that lacks the WIFEXITED preprocessor macro in its headers. It's not worth the effort, please make it BSD specific.

**Pull request merged**
