### PR TITLE
Fix a typo in "raises" annotation description.

### PR DESCRIPTION
**Pull request by eventualbuddha**

### CODE REVIEW

**Comment by def-** [comment]
Was it intentional that this was on the master branch instead of devel?

**Comment by dom96** [comment]
All PRs should be made against devel. This may just lead to conflicts in the future.

**Comment by eventualbuddha** [comment]
Hmm, odd. I'm not sure how that happened. I just did the usual "Edit" -> "Propose file change" which should have used the default branch of "devel". My apologies.

**Comment by def-** [comment]
When you click on "view source" on the documentation, you land on the master branch. This seems to happen rather often, not sure how to solve it.

**Pull request merged**
