### PR TITLE
New Editor (LiClipse)

### PR DESCRIPTION
**Pull request by fabioz**

### CODE REVIEW

**Comment by def-** [comment]
This should've been on devel, not master.

**Comment by fabioz** [comment]
Humm, I must say that I was lead to that because I just followed the link: https://github.com/Araq/Nim/blob/master/web/question.txt which is provided from the Wiki: https://github.com/Araq/Nim/wiki/Editor-Support and did it all through the github web interface -- so, probably that link should be changed to: https://github.com/Araq/Nim/blob/devel/web/question.txt ?

I guess at this point the best would be just cherry picking that to devel (do you want me to create a pull request for that?)

**Comment by Araq** [comment]
@fabioz don't bother I updated devel for you.

**Comment by fabioz** [comment]
Ok, as a note, as you reverted on master, you probably have to not only cherry-pick on devel, you also have to cherry-pick the revert and then make a new commit to revert the revert on devel (otherwise when you merge master the change will already be reverted)...

**Pull request merged**
