### PR TITLE
db: InstantRow and instantRows

### PR DESCRIPTION
**Pull request by nanoant**
## db: InstantRow and instantRows

It is drop-in replacement for `Row` and `fastRows`, however `instantRows` returns a
handle, not `seq[string]`, so no Nim string is created until `[]` operator is
called on the given handle. Also there is a `len()` proc returning number of
columns in the handle.

In some situations, when we iterate through many rows, but later we just read
few columns this solution will be quicker than converting all column to Nim
`seq[string]` on each iteration.

### CODE REVIEW

**Comment by kirbyfan64** [comment]
Shouldn't it be `DeferredRow` now?

**Comment by nanoant** [comment]
@kirbyfan64 Maybe, but until rest is having `T` prefix, I prefer to leave it as is. I think modernizing this modules should be made with other commit.

**Comment by nanoant** [comment]
FYI renamed `deferredRows` to `instantRows` as it represent better what the iterator does, also *deferred* might misguide that the given handle could be used out of the iterator loop ("later").

**Comment by nanoant** [comment]
@kirbyfan64 Rebased and reflect latest changes dropping `T` prefix.

**Pull request merged**
