### PR TITLE
Add git sha1 to compiler version info and docgen.

### PR DESCRIPTION
**Pull request by winksaville**
This helps to more precisely define the version of the compiler when using -v.
Also adds the sha1 to the html created by docgen.

### CODE REVIEW

**Comment by reactormonk** [comment]
Please test the changes via `./koch temp hello_world.nim`

**Comment by winksaville** [comment]
I'm really sorry, I merged from a previous branch and hadn't tested test on this branch.

**Comment by winksaville** [comment]
Here is the output of -v from the new branch:

```
wink@desktop:~/foss/wink-nim$ bin/nim -v
Nim Compiler Version 0.10.3 f59186b5fdd57ae18f206838e41973054c89f9fd
(2015-04-05) [Linux: amd64] Copyright (c) 2006-2015 by Andreas Rumpf

active boot switches: -d:release
wink@desktop:~/foss/wink-nim$ 
```

At least one change might be to shorten the output of the sha1 to 20 or even 10 characters or ...

**Comment by reactormonk** [comment]
github uses 6 chars, go for that number.

**Comment by dom96** [comment]
This was implemented before but it was removed at some point, perhaps there is still code left over for it?

**Comment by winksaville** [comment]
Yes the code is there in writeVersionInfo, I hadn't noticed it. It was disabled on 2014-09-28 by @Varriount with change b234d311d49df927b709891f5f640b90cf982ee4. The commit message says:
```
Disable git hashing in the version command
```
But gives no reason, I think have the hash is important and allows people to know more precisely what version was used. This is particularly important on the devel branch where it would be good to know when a bug is reported what the state of the tree was, that's why I added it.

My code also emits the Sha1 in all variants of displaying the HelpMessage and I also added it to docgen so the Sha1 shows up in the generated html file, which people may or may not like.

So we could just reenable or modify the old code or a combination of mine and the old code. In any case we should find out why the old code was disabled, hopefully @Araq or Varriount can fill us in.

**Comment by Araq** [comment]
This can already be done with 'gorge' and built into the compiler is foolish, not every project uses git. Let's enable it in commands.writeVersionInfo instead again now that 'gorge' is fixed and does a minimal amount of error checking.

**Pull request closed without merging**
